### ISSUE TITLE
Bad Request: wrong file identifier/HTTP URL specified

### ISSUE THREAD

**Issue by BigTows** [haishanh/actions-telegram-notification#9]
Hi!
I am use your action with next params:
```yaml
      - uses: haishanh/actions-telegram-notification@v1
        with:
          bot-token: ${{ secrets.TG_NOTIFICATION_TOKEN }}
          chat-id: ${{ secrets.TG_CHAT_ID }}
          job-status: ${{ job.status }}
```

and I get:
```json
{"ok":false,"error_code":400,"description":"Bad Request: wrong file identifier/HTTP URL specified"}
```
This is my bad or bug?
